In [2]:
#Import library
import tensorflow as tf
import numpy as np

In [3]:
#Check the tensorflow version
tf.__version__

'2.3.1'

## 01 - Tensores
#### Each tensor has a series of properties, notably:

- **dtype**, the type of data stored internally.
- **rank**, also known as order or degree of the tensor, tells how many dimensions the tensor has.
- **shape**, the internal shape, that is, the dimensions of this tensor as a multidimensional arrangement.
- **device**, the name of the device on which this tensioner will be produced.

#### There are two types of tensioners in TensorFlow:

- **constant**. they have fixed dimensions and the stored values are also fixed since its creation. They are generally used for hyperparameters and structured data that should be protected from change.
- **variables**. they also have fixed dimensions, but the stored values can be changed. Used to store weight and other data that change over the course of training or activation.

## Constants

In [13]:
# Create constant tensor with 2x2 dimension, the type int32
tensor_01 = tf.constant([[1,2], [3,4]], shape=[2,2],dtype=tf.int32)
print(tensor_01)

tf.Tensor(
[[1 2]
 [3 4]], shape=(2, 2), dtype=int32)


In [21]:
#show the value in tensor
print("tensor_01.numpy():",tensor_01.numpy())

#show the device
print("tensor_01.device:",tensor_01.device)

#show the type
print("tensor_01.dtype:",tensor_01.dtype)

#show the shape
print("tensor_01.shape:",tensor_01.shape)

#show the rank
print("rank:",len(tensor_01.numpy()))

tensor_01.numpy(): [[1 2]
 [3 4]]
tensor_01.device: /job:localhost/replica:0/task:0/device:CPU:0
tensor_01.dtype: <dtype: 'int32'>
tensor_01.shape: (2, 2)
rank: 2


## tf.zeros & tf.ones

- **input** 	A Tensor or array-like object.
- **dtype**	The DType of an element in the resulting Tensor.
- **name**	Optional string. A name for the operation.

In [23]:
# creates a 2x2 matrix filled with zeros
zeros_a = tf.zeros( shape=[2,2], dtype=tf.int32, name='zeros_a' )
print(zeros_a)

# creates a 2x4 matrix filled with ones
ones_a = tf.ones( shape=[2,4], dtype=tf.float32, name='zeros_a' )
print(ones_a)

tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]], shape=(2, 4), dtype=float32)


## tf.fill

In [ ]:
filled_ei  = tf.fill( [3,2], 6)
filled_ef = tf.fill( [3,2], 6.0)
print(filled_ei)
print(filled_ef)
